"""Stage 3 - Header & Email Forensics orchestrator."""
from __future__ import annotations

import re

from app.core.utils import registrable_domain
from app.services.findings import ev, finding
from app.services.threat_detection.rules import FREEMAIL
from app.services.header_forensics.authentication import check_dkim, check_dmarc, check_spf, parse_receiver_results
from app.services.header_forensics.received import build_received_chain, pick_sending_ip

SUSPICIOUS_MAILERS = re.compile(r"phpmailer|sendblaster|atomic mail|mass ?mail|bulk ?mail|swaks|python|smtplib|curl|powershell|leaf", re.IGNORECASE)


def _msgid_domain(message_id: str | None) -> str | None:
    if not message_id:
        return None
    m = re.search(r"@([^>\s]+)>?", message_id)
    return m.group(1).lower() if m else None


def analyze_headers(parsed: dict, raw: bytes) -> tuple[dict, list]:
    h = parsed["headers"]
    from_hdr = h.get("from") or {}
    from_domain = from_hdr.get("domain")
    findings = []

    hops, anomalies = build_received_chain(parsed["received"], h.get("date_iso"))
    final_receiver = hops[-1]["server"] if hops else None
    receiver = parse_receiver_results(parsed["authentication_results"], parsed["received_spf"], final_receiver)
    sending = pick_sending_ip(hops, receiver.get("client_ip") if receiver.get("trusted") else None)

    mail_from = (h.get("return_path") or {}).get("address") or receiver.get("smtp_mailfrom")
    spf_res = check_spf(sending.get("ip"), mail_from, from_domain, sending.get("helo"), receiver)
    dkim_res = check_dkim(raw, parsed["dkim_signatures"], receiver)
    dmarc_res = check_dmarc(from_domain, spf_res, dkim_res, receiver)

    # ---- identity relationships
    identities = {
        "from": from_domain,
        "reply_to": (h.get("reply_to") or {}).get("domain"),
        "return_path": (h.get("return_path") or {}).get("domain"),
        "message_id": _msgid_domain(h.get("message_id")),
        "sender": (h.get("sender") or {}).get("domain"),
        "dkim_d": dkim_res.get("domain"),
    }
    from_org = registrable_domain(from_domain)
    mismatches = []
    for field, dom in identities.items():
        if field == "from" or not dom:
            continue
        match = registrable_domain(dom) == from_org
        mismatches.append({"field": field, "domain": dom, "from_domain": from_domain, "aligned_with_from": match})

    def mm(field):
        return next((m for m in mismatches if m["field"] == field and not m["aligned_with_from"]), None)

    from_id = f"email:{from_hdr.get('address')}" if from_hdr.get("address") else None
    if (m := mm("reply_to")):
        findings.append(finding(
            "F-ID-REPLYTO-MISMATCH", category="identity", severity="medium", confidence="high",
            title="Reply-To domain differs from From domain",
            description=f"Replies will go to {h['reply_to']['address']} although the message claims to be from {from_hdr.get('address')}.",
            why="Attackers spoof a trusted From address and redirect replies to a mailbox they control. Some legitimate services also do this, so it is combined with other evidence.",
            evidence=[ev("From", from_hdr.get("raw"), "From header"), ev("Reply-To", h["reply_to"]["raw"], "Reply-To header")],
            sources=["header_forensics"], related=[x for x in [from_id, f"email:{h['reply_to']['address']}"] if x], module="header_forensics",
            finding_type="observed_fact"))
    if (m := mm("return_path")):
        findings.append(finding(
            "F-ID-RETURNPATH-MISMATCH", category="identity", severity="low", confidence="medium",
            title="Return-Path (envelope sender) domain differs from From domain",
            description=f"Bounce address domain {m['domain']} vs From domain {from_domain}.",
            why="Common for newsletters/ESPs, but also used in spoofing: SPF is checked against the Return-Path, not the visible From.",
            evidence=[ev("Return-Path", h["return_path"]["raw"], "Return-Path header"), ev("From", from_hdr.get("raw"), "From header")],
            sources=["header_forensics"], related=[x for x in [from_id, f"domain:{m['domain']}"] if x], module="header_forensics",
            finding_type="observed_fact"))
    if (m := mm("message_id")):
        findings.append(finding(
            "F-ID-MSGID-MISMATCH", category="identity", severity="low", confidence="low",
            title="Message-ID domain differs from From domain",
            description=f"Message-ID was generated by {m['domain']}, not {from_domain}.",
            why="The Message-ID usually reveals the software/system that created the email; a different domain can reveal the real origin.",
            evidence=[ev("Message-ID", h.get("message_id"), "Message-ID header")], sources=["header_forensics"],
            related=[f"domain:{m['domain']}"], module="header_forensics", finding_type="observed_fact"))

    # ---- authentication findings
    spf_s, dkim_s, dmarc_s = spf_res["status"], dkim_res["status"], dmarc_res["status"]
    if spf_s in ("fail", "softfail"):
        findings.append(finding(
            "F-AUTH-SPF-FAIL", category="authentication", severity="medium" if spf_s == "fail" else "low", confidence="high" if spf_res["status_source"] == "independent_check" else "medium",
            title=f"SPF {spf_s.upper()} for {spf_res['domain']}",
            description=f"Sending IP {spf_res['ip']} is not authorised by the SPF policy of {spf_res['domain']}. {spf_res['evidence']}",
            why="The server that delivered the email is not on the domain's list of allowed senders. Forwarding can also cause this, so it is not proof on its own.",
            evidence=[ev("SPF result", spf_s, spf_res["status_source"]), ev("Sending IP", spf_res["ip"], sending["method"])],
            sources=["spf"], related=[f"ip:{spf_res['ip']}" if spf_res["ip"] else "", f"domain:{spf_res['domain']}"], module="header_forensics"))
    if dkim_s == "fail":
        findings.append(finding(
            "F-AUTH-DKIM-FAIL", category="authentication", severity="medium", confidence="medium",
            title="DKIM signature failed verification", description=dkim_res["evidence"],
            why="The message was altered after signing or signed with a key the domain did not publish.",
            evidence=[ev("DKIM", dkim_res["evidence"], dkim_res["status_source"])], sources=["dkim"],
            related=[f"domain:{dkim_res['domain']}"] if dkim_res.get("domain") else [], module="header_forensics"))
    if dmarc_s == "fail":
        findings.append(finding(
            "F-AUTH-DMARC-FAIL", category="authentication", severity="high" if dmarc_res.get("policy") in ("reject", "quarantine") else "medium",
            confidence="high" if dmarc_res["status_source"] == "independent_check" else "medium",
            title=f"DMARC FAIL for {from_domain}" + (f" (policy p={dmarc_res['policy']})" if dmarc_res.get("policy") else ""),
            description=dmarc_res["evidence"],
            why="No authentication result is aligned with the visible From domain, which is exactly what From-spoofing looks like.",
            evidence=[ev("SPF alignment", dmarc_res["spf_alignment"]), ev("DKIM alignment", dmarc_res["dkim_alignment"]),
                      ev("DMARC record", dmarc_res.get("record"), "DNS")],
            sources=["dmarc"], related=[f"domain:{from_domain}"], module="header_forensics"))
    elif dmarc_s == "pass":
        freemail = (from_domain or "") in FREEMAIL
        findings.append(finding(
            "F-AUTH-DMARC-PASS", category="mitigating", severity="info",
            confidence="low" if freemail else "high" if dmarc_res["status_source"] == "independent_check" else "medium",
            title=f"DMARC PASS for {from_domain}", description=dmarc_res["evidence"] + (" (free webmail domain: anyone can register an account, so this proves little about the sender)" if freemail else ""),
            why="The visible From domain is authenticated. This lowers spoofing risk, but a compromised, free-webmail or look-alike domain can still pass.",
            evidence=[ev("DMARC", "pass", dmarc_res["status_source"])], sources=["dmarc"], related=[f"domain:{from_domain}"],
            module="header_forensics"))
    if dmarc_s == "none" and from_domain:
        findings.append(finding(
            "F-AUTH-NO-DMARC", category="authentication", severity="info", confidence="medium",
            title=f"No DMARC policy for {from_domain}", description=dmarc_res["evidence"],
            why="Without DMARC, receivers have no policy telling them to reject spoofed mail from this domain.",
            sources=["dmarc"], related=[f"domain:{from_domain}"], module="header_forensics", finding_type="observed_fact"))
    for mech, res in (("spf", spf_res), ("dkim", dkim_res)):
        if res.get("disagreement"):
            findings.append(finding(
                f"F-AUTH-{mech.upper()}-DISAGREE", category="authentication", severity="low", confidence="low",
                title=f"{mech.upper()}: our check disagrees with the receiving server",
                description=f"Independent check '{res['independent_check']}' vs receiver-recorded '{res['receiver_reported']}'.",
                why="DNS may have changed since delivery, or the Authentication-Results header was altered.",
                sources=[mech], module="header_forensics"))
    if receiver.get("present") and not receiver.get("trusted"):
        findings.append(finding(
            "F-HDR-UNTRUSTED-AUTHRESULTS", category="header", severity="low", confidence="medium",
            title="Authentication-Results header not added by the final receiving server",
            description=f"authserv-id '{receiver.get('authserv_id')}' does not match the final receiver '{final_receiver}'. It was ignored.",
            why="Senders can insert fake Authentication-Results headers claiming 'pass'.",
            evidence=[ev("Authentication-Results", receiver.get("raw"))], sources=["header_forensics"], module="header_forensics"))

    # ---- routing anomalies
    for a in anomalies:
        if a["severity"] in ("low", "medium"):
            findings.append(finding(
                f"F-ROUTE-{a['code'].upper().replace('_', '-')}" + (f"-H{a['hop']}" if a.get("hop") else ""),
                category="routing", severity=a["severity"], confidence="low",
                title=a["description"], description=a["description"], why=a["interpretation"],
                sources=["received_chain"], module="header_forensics", finding_type="observed_fact"))

    # ---- other header indicators
    mailer = h.get("x_mailer") or h.get("user_agent")
    if mailer and SUSPICIOUS_MAILERS.search(mailer):
        findings.append(finding(
            "F-HDR-SUSPICIOUS-MAILER", category="header", severity="low", confidence="medium",
            title=f"Bulk/script mailing software: {mailer}",
            description="The X-Mailer/User-Agent header names software often used for scripted or bulk sending.",
            why="Corporate mail normally comes from standard mail servers; phishing kits frequently use PHPMailer and similar tools.",
            evidence=[ev("X-Mailer / User-Agent", mailer)], sources=["header_forensics"], module="header_forensics", finding_type="observed_fact"))
    missing = [name for name, val in (("Message-ID", h.get("message_id")), ("Date", h.get("date"))) if not val]
    if missing:
        findings.append(finding(
            "F-HDR-MISSING", category="header", severity="low", confidence="medium",
            title="Missing standard header(s): " + ", ".join(missing),
            description="Normal mail clients and servers always add these headers.",
            why="Hand-crafted or script-generated messages often omit them.", sources=["header_forensics"],
            module="header_forensics", finding_type="observed_fact"))
    if parsed.get("encoded_headers"):
        findings.append(finding(
            "F-HDR-ENCODED", category="header", severity="info", confidence="low",
            title="Encoded (RFC 2047) header values", description="Encoded headers: " + ", ".join(parsed["encoded_headers"]),
            why="Encoding is normal for non-English text but is also used to hide look-alike characters from filters.",
            sources=["header_forensics"], module="header_forensics", finding_type="observed_fact"))

    for f in findings:
        f.related_indicators = [r for r in f.related_indicators if r]

    return {
        "important_headers": {k: h.get(k) for k in ("subject", "date", "message_id", "x_mailer", "user_agent", "x_originating_ip", "mime_version")},
        "identity": {"domains": identities, "comparisons": mismatches},
        "received_chain": hops,
        "routing_path": [{"hop": x["hop"], "from": x["hostname"] or x["ip"], "ip": x["ip"], "to": x["server"], "timestamp": x["timestamp"]} for x in hops],
        "anomalies": anomalies,
        "sending_ip": sending,
        "authentication": {"spf": spf_res, "dkim": dkim_res, "dmarc": dmarc_res, "receiver_reported": receiver},
    }, findings
